global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nginx_reverse_proxy"
    static_configs:
      - targets:
          - "192.168.1.36:9113"

  - job_name: "server-sma-apache"
    static_configs:
      - targets:
          - "192.168.1.54:9117"

